 FORCE PAIR LOGIC FOR ALL REFERENCE PAIRS in matches_NLP_list_ERP suggested X-match
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.20624423027038574 seconds
Traceback (most recent call last):
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'CHILD_NM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cross_hound/matcher.py", line 1851, in <module>
    main(input_dir=args.get('input_dir'),
  File "cross_hound/matcher.py", line 1629, in main
    matched, unmatched = full_matching_routine(data_version, db_style, device,
  File "cross_hound/matcher.py", line 1119, in full_matching_routine
    matches_NLP_list_ERP, erp_to_match, tru_to_match, previous_round = match_by_reference_table(erp_to_match,
  File "cross_hound/matcher.py", line 453, in match_by_reference_table
    df[TRU_SPEC_ID] = df[TRU_SPEC_ID].astype(str).str.strip()
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/frame.py", line 3760, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'CHILD_NM'

