üîÑ FORCE PAIR LOGIC FOR UNMATCHED REFERENCE PAIRS
‚úÖ COMP ID 528926 FOUND in full ERP (erp_full)
‚úÖ CHILD NUM PC-0014319 FOUND in full TRU (tru_full)
üö® Running FORCE PAIR matching for matches_NLP_list_ERP suggested X-match üö®
‚ö†Ô∏è 1493 unmatched reference pairs for forced pair logic.
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.17124080657958984 seconds
Traceback (most recent call last):
  File "cross_hound/matcher.py", line 1730, in <module>
    main(input_dir=args.get('input_dir'),
  File "cross_hound/matcher.py", line 1514, in main
    matched, unmatched = full_matching_routine(data_version, db_style, device,
  File "cross_hound/matcher.py", line 1332, in full_matching_routine
    matches_NLP_list_ERP, erp_to_match, tru_to_match, previous_round = match_by_reference_table(erp_to_match,
  File "cross_hound/matcher.py", line 497, in match_by_reference_table
    forced_matches = erp_full[ERP_MATCH_COLS].merge(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/frame.py", line 9843, in merge
    return merge(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 142, in merge
    op = _MergeOperation(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 713, in __init__
    self.left_on, self.right_on = self._validate_left_right_on(left_on, right_on)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1536, in _validate_left_right_on
    raise ValueError("len(right_on) must equal len(left_on)")
ValueError: len(right_on) must equal len(left_on)

